[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@next/font", "sharp", "next", "react", "react-dom"]
  included_files = []
  
[build]
  command = "npm run netlify-build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_SPLIT_API_ROUTES = "true"
  NEXT_FORCE_EDGE_RUNTIME = "true"