[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@next/font", "sharp"]
  included_files = []
  
[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_SPLIT_API_ROUTES = "true"
  NEXT_FORCE_EDGE_RUNTIME = "true"