backend:
  name: git-gateway
  publish_mode: editorial_workflow

commit_messages:
  create: Create {{collection}} “{{slug}}”
  update: Update {{collection}} “{{slug}}”
  delete: Delete {{collection}} “{{slug}}”
  uploadMedia: Upload “{{path}}”
  deleteMedia: Delete “{{path}}”
  openAuthoring: "{{message}}"

media_folder: "public/uploads"
media_library:
  name: uploadcare
  config:
    publicKey: demopublickey

site_url: https://ingnova.netlify.app
display_url: https://ingnova.netlify.app
locale: "es"
show_preview_links: false

slug:
  encoding: "ascii"
  sanitize_replacement: "_"

collections:
  - name: "service"
    label: "Service"
    folder: "_posts/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripión", name: "description", widget: "text" }
      - { label: "Imágen", name: "image", widget: "image" }
