backend:
  name: git-gateway
  branch: master
  publish_mode: editorial_workflow

commit_messages:
  create: create {{collection}} "{{slug}}"
  update: update {{collection}} "{{slug}}"
  delete: delete {{collection}} "{{slug}}"
  uploadMedia: upload "{{path}}"
  deleteMedia: delete "{{path}}"
  openAuthoring: "{{message}}"

site_url: https://rdingnova.com.co
display_url: https://rdingnova.com.co
locale: "es"
show_preview_links: false

slug:
  encoding: "unicode"
  sanitize_replacement: "_"
  clean_accents: true

media_library:
  name: cloudinary
  config:
    cloud_name: dtlfttst9
    api_key: 542592619219557

collections:
  # 🛠️ Services Page (Multiple entries)
  - name: "services"
    label: "Servicios"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Ícono", name: "icon", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
      - {
          label: "Destacado",
          name: "featured",
          widget: "boolean",
          default: false,
        }
      - { label: "Contenido", name: "body", widget: "markdown" }

  # 📌 Equipos (Equipment) Section
  - name: "equipment"
    label: "Equipos"
    folder: "content/equipment"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Contenido", name: "body", widget: "markdown" }

  # 🏗️ Projects Page (Multiple entries)
  - name: "projects"
    label: "Proyectos"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Categoría", name: "category", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Ubicación", name: "location", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime", required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }

  # Stats - Home (Multiple entries)
  - name: "stats"
    label: "Estadísticas"
    folder: "content/stats"
    create: true
    slug: "{{label}}"
    fields:
      - { label: "Número", name: "number", widget: "string" }
      - { label: "Etiqueta", name: "label", widget: "string" }

  # Values - About (Multiple entries)
  - name: "values"
    label: "Valores"
    folder: "content/values"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Ícono", name: "icon", widget: "string" }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }

  # Team - About (Multiple entries)
  - name: "team"
    label: "Personal Clave"
    folder: "content/team"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Nombre", name: "name", widget: "string" }
      - { label: "Cargo", name: "position", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Biografía", name: "bio", widget: "markdown", required: false }

  # FAQs - Contact (Multiple entries)
  - name: "faqs"
    label: "Preguntas Frecuentes"
    folder: "content/faqs"
    create: true
    slug: "{{question}}"
    fields:
      - { label: "Pregunta", name: "question", widget: "string" }
      - { label: "Respuesta", name: "answer", widget: "text" }

  # Pages (file collections)
  - name: "pages"
    label: "Páginas"
    files:
      - file: "content/home.md"
        label: "Página de Inicio"
        name: "home"
        fields:
          - { label: "Hero Fondo", name: "heroBg", widget: "image" }
          - { label: "Hero Título", name: "heroTitle", widget: "string" }
          - { label: "Hero Subtítulo", name: "heroSubtitle", widget: "string" }
          - {
              label: "Servicios Título",
              name: "servicesTitle",
              widget: "string",
            }
          - {
              label: "Servicios Descripción",
              name: "servicesDescription",
              widget: "string",
            }
          - { label: "CTA Título", name: "ctaTitle", widget: "string" }
          - {
              label: "CTA Descripción",
              name: "ctaDescription",
              widget: "string",
            }
          - { label: "CTA Botón", name: "ctaButton", widget: "string" }
          - {
              label: "Estadísticas",
              name: "statsItems",
              widget: "relation",
              collection: "stats",
              search_fields: ["label"],
              value_field: "{{slug}}",
              multiple: true,
            }

      - file: "content/about.md"
        label: "Página Sobre Nosotros"
        name: "about"
        fields:
          - { label: "Hero Fondo", name: "heroBg", widget: "image" }
          - { label: "Hero Título", name: "heroTitle", widget: "string" }
          - { label: "Hero Subtítulo", name: "heroSubtitle", widget: "string" }
          - { label: "Historia Título", name: "historyTitle", widget: "string" }
          - {
              label: "Historia Contenido",
              name: "historyContent",
              widget: "markdown",
            }
          - { label: "Historia Imagen", name: "historyImage", widget: "image" }
          - { label: "Valores Título", name: "valuesTitle", widget: "string" }
          - {
              label: "Valores Descripción",
              name: "valuesDescription",
              widget: "string",
            }
          - {
              label: "Valores",
              name: "valueItems",
              widget: "relation",
              collection: "values",
              search_fields: ["title"],
              value_field: "{{slug}}",
              multiple: true,
            }
          - {
              label: "Equipo",
              name: "teamMembers",
              widget: "relation",
              collection: "team",
              search_fields: ["name"],
              value_field: "{{slug}}",
              multiple: true,
            }

      - file: "content/services.md"
        label: "Página Servicios"
        name: "services"
        fields:
          - { label: "Hero Fondo", name: "heroBg", widget: "image" }
          - { label: "Hero Título", name: "heroTitle", widget: "string" }
          - { label: "Hero Subtítulo", name: "heroSubtitle", widget: "string" }
          - {
              label: "Servicios Título",
              name: "servicesTitle",
              widget: "string",
            }
          - {
              label: "Servicios Contenido",
              name: "servicesContent",
              widget: "markdown",
            }
          - {
              label: "Servicios",
              name: "servicesItems",
              widget: "relation",
              collection: "services",
              search_fields: ["title"],
              value_field: "{{slug}}",
              multiple: true,
            }
          - {
              label: "Equipo Título",
              name: "equipmentTitle",
              widget: "string",
            }
          - {
              label: "Equipo Contenido",
              name: "equipmentContent",
              widget: "markdown",
            }
          - {
              label: "Equipo",
              name: "equipmentItems",
              widget: "relation",
              collection: "equipment",
              search_fields: ["title"],
              value_field: "{{slug}}",
              multiple: true,
            }

      - file: "content/projects.md"
        label: "Página Proyectos"
        name: "projects"
        fields:
          - { label: "Hero Fondo", name: "heroBg", widget: "image" }
          - { label: "Hero Título", name: "heroTitle", widget: "string" }
          - { label: "Hero Subtítulo", name: "heroSubtitle", widget: "string" }
          - {
              label: "Proyectos Título",
              name: "projectsTitle",
              widget: "string",
            }
          - {
              label: "Proyectos Contenido",
              name: "projectsContent",
              widget: "markdown",
            }
          - {
              label: "Proyectos",
              name: "projectsItems",
              widget: "relation",
              collection: "projects",
              search_fields: ["title"],
              value_field: "{{slug}}",
              multiple: true,
            }

      - file: "content/contact.md"
        label: "Contacto"
        name: "contact"
        fields:
          - { label: "Hero Fondo", name: "heroBg", widget: "image" }
          - { label: "Hero Título", name: "heroTitle", widget: "string" }
          - { label: "Hero Subtítulo", name: "heroSubtitle", widget: "string" }
          - { label: "Descripción", name: "description", widget: "text" }
          - { label: "Dirección", name: "address", widget: "string" }
          - { label: "Teléfono", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Horario", name: "schedule", widget: "string" }
          - { label: "Instagram Link", name: "instagram", widget: "string" }
          - { label: "Facebook Link", name: "facebook", widget: "string" }
          - { label: "LinkedIn Link", name: "linkedin", widget: "string" }
          - { label: "Youtube Link", name: "youtube", widget: "string" }
          - {
              label: "FAQs",
              name: "faqItems",
              widget: "relation",
              collection: "faqs",
              search_fields: ["question"],
              value_field: "{{slug}}",
              multiple: true,
            }
